### ISSUE TITLE
worldserver.exe crash

### ISSUE THREAD

**Issue by princesbem** [Smolderforge/issues#415]
Hello there.. im trying to build skyfireone source and every source of skyfire like tbcpvp smolderforge source skyfireone i tried all of the sources on github and after compilling and setting up everything worldserver.exe doesnt start.. can someone help me to build that source correctly? i dont found any guide and any issues about the compilling it seems like only i have this problem or idk.. please help me to build it i just want it for training .. maybe i use incorrect requirements or idk 
thanks

**Comment by henhouse** [comment]
Sorry, this isn't a support for running your own server.
