### ISSUE TITLE
[Rogue] Envenom does not benefit from Dirty Deeds talent

### ISSUE THREAD

**Issue by ghost** [Smolderforge/issues#428]
The problem: The rogue ability "Envenom" does not benefit from the 20% extra bonus damage to targets at or under 35% health from the Dirty Deeds talent.

How it should work: If the enemy target is at or under 35% health Envenom should deal an additional 20% damage.

How to reproduce: Make a rogue and stack 5x stacks of Deadly Poison on an enemy over 35% health and use Envenom. Note the damage down. Now do the same thing again but when the enemy is at or under 35% health. The damage will be the same as before.

**Comment by henhouse** [comment]
Will be fixed next restart.
