### ISSUE TITLE
[Hunter] Aimed shot supposed to be 2.5s, not 3

### ISSUE THREAD

**Issue by bbatey** [Smolderforge/issues#457]
>Bc icon Patch 2.3.0 (13-Nov-2007): Added reduction of healing done to that target by 50%, shot time reduced by 0.5 seconds to 2.5 seconds. The reduced healing effect does not stack with Warriors' Mortal Strike or with Rogues'

Aimed shot in game is still 3s and on tooltip shows 3s.

**Comment by henhouse** [comment]
It's not common that Blizzard tooltips are incorrect. It's especially weird that they never would have fixed this incorrect tooltip all the way until the final patch 2.4.3 (9 months between the two). However, there is no patch between then that mentions it rising back to 3.0, either. The 3 seconds is defined by the game files, themselves, not us.

However, I was able to find this video quickly on YouTube. Possibly evidence. Couldn't find any bug reports on Corecraft's old repo; may look else where. This is either an insanely obscure bug that no one has noticed, or isn't. I cannot tell just yet.

Possibly evidence:
https://youtu.be/4jbSgaPROH0?t=56

**Comment by bugreport4** [comment]
https://youtu.be/NoKD723_yAM?t=496 S3 2.5

**Comment by sunofabeachgodxqt** [comment]
Patch 2.3.0 (2007-11-13): Added reduction of healing done to that target by 50% and cast time was **reduced to 3 sec from 3.5 sec.** The reduced healing effect does not stack with Warriors' Mortal Strike or with Rogues' Wound Poison. 
https://wowwiki-archive.fandom.com/wiki/Aimed_Shot?oldid=1636963
https://wowpedia.fandom.com/wiki/Aimed_Shot#Patches%20and%20hotfixes

**Comment by henhouse** [comment]
Closing as invalid. Confirmed Aim Shot is 3-seconds cast on TBC Classic beta.
