### ISSUE TITLE
Flask of Petrification TBC

### ISSUE THREAD

**Issue by drakgoku** [Smolderforge/issues#461]
Hello,

I can't use Flask of Petrification, because jump this message:
"the spell is not available to you"

fix it.

Regards.

**Comment by henhouse** [comment]
It's intentionally disabled. We don't really find it has any place in TBC PvP, especially when people can craft unlimited amounts freely. The debuff cannot be removed by the caster, so even if we limited the amount players can carry... it's not really serving any purpose in PvP other than being annoying to everyone--which is exactly why we removed it.

**Comment by drakgoku** [comment]
His argument does not make any sense.

"We don't really find it has any place in TBC PvP,"

This statement with the PVP lacks common sense with the item. "Use: You turn to stone, protecting you from all physical attacks and spells for 1 min, but during that time you cannot attack, move or cast spells. You can only have the effect of one flask at a time."

Also the item "Free action potion" you can only take 5.

I understand that they want to have a server and do not understand the PVP people. It is understandable. But the official developers do not think in the same way.

I understand that "novice programmers" do not want to use 100% of the items because they believe that it unbalances the game, so Blizzard has some programmers and analysts who confirm what can be used and what cannot be used.

It is normal that people who want to prepare for TBC cannot do it correctly.

Regrettable. Do what you want and give it time for your test server to go down.

**Comment by drakgoku** [comment]
Well, even though a lot of random issues were exposed, your server doesn't make any sense at all.

I am not able to understand why they open a server (any newbie can do it having a server) and they do not solve:
1 - The quests
2 - The items
3 - General resources (potions, flask, ...)
4 - Errors in the classes
  - Example: The rogue in stealth cannot take the flag
  - Example: The rogue in stealth cannot catch the buff from BG because it disappears
- Endless mistakes.
5 - Problems with the skills of "all classes"
6 - You disable flask at your convenience ... (which is what it has been about)
- That is, according to you, you are more professional than Blizzard in these decisions? How funny, where do you come from?
7 - etc ... What am I going to explain that you do not know ...

As an experienced programmer, I think that the team of 4 or 5 people that you surely have is lamentable.

Good luck with that team "policy", the less the better.
